name: Build wg-easy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies & build (frontend)
        run: |
          cd src
          NUXT_TELEMETRY_DISABLED=1 pnpm install --frozen-lockfile
          pnpm build

      - name: Archive build outputs
        run: |
          cd src
          tar -czf wg-easy-output.tar.gz .output
          mv wg-easy-output.tar.gz $GITHUB_WORKSPACE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wg-easy-output
          path: wg-easy-output.tar.gz
          
      - name: Move latest tag to HEAD and push
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin master
          git checkout master
          git tag -d latest || true
          git push https://${GH_TOKEN}@github.com/${{ github.repository }} :refs/tags/latest || true
          git tag -a latest -m "Auto tag to latest at $(date)"
          git push https://${GH_TOKEN}@github.com/${{ github.repository }} latest --force

      - name: Create or Update Release on latest tag
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest Release
          body: |
            This release is automatically published at the HEAD of the main branch. Every push to main automatically refreshes the latest tag and artifacts.
          allowUpdates: true               
          replacesArtifacts: true             
          artifacts: wg-easy-output.tar.gz 
          token: ${{ secrets.PUSH_TOKEN }}
